### ISSUE TITLE
can’t get it on ps5

### ISSUE THREAD

**Issue by BigScar1017** [RavinMaddHatter/Bedrock-Chunk-Boarders-Pack#17]

**Comment by BigScar1017** [comment]
help me

**Comment by BigScar1017** [comment]
got it to work on my ios but when i activate it, it's not on my ps5 and i tried doing it through the website on my ps5 and it says the file data is not supported by ps5

**Comment by RavinMaddHatter** [comment]
That isn't a structura bug or a Minecraft bug. That is an intended feature
of the PS5.

You can put it on a server, realm, or local world on a different device,
force pack download and it will work just fine.

This is not a bug. This is how sony wants it to be
