### ISSUE TITLE
Not working in 1.20.62.02

### ISSUE THREAD

**Issue by 7ooL** [RavinMaddHatter/Bedrock-Chunk-Boarders-Pack#18]
just added it to new world, Bedrick Dedicated Server and it doesn't appear to work. Bedrock-server-1.20.62.02

**Comment by RavinMaddHatter** [comment]
Works for me... But move to the technical resource pack

**Comment by 7ooL** [comment]
Not sure what you mean "move to the technical resource pack". I have one folder called resource_packs and in my worlds folder i refences specific packs using the  world_resource_packs.json file. 

Edit: Sorry, I just found your other repository, I'll try that pack out.

**Comment by RavinMaddHatter** [comment]
99% sure you are not in 3rd person or you have more than 1 texture pack on.
But this project was abandoned for a new one called bedrock technical
resource pack. It has more stuff

**Comment by 7ooL** [comment]
Thank you. I was likely not in 3rd person, new world, it's been 6 months since last using it, forgot about 3rd person. I'll check out your new pack.
