### ISSUE TITLE
Character creator skins become Steve

### ISSUE THREAD

**Issue by waggers5** [RavinMaddHatter/Bedrock-Chunk-Boarders-Pack#2]
Any skins made using Character Creator become the default Steve skin when the pack is active in Global Resources.
When trying to edit a skin in Character Creator with the pack active, none of the changes take effect.
Disabling the pack makes the skins render properly once more.

v1.16.210 on Windows 10

**Comment by kimonxx** [comment]
> 
> 
> Any skins made using Character Creator become the default Steve skin when the pack is active in Global Resources.
> When trying to edit a skin in Character Creator with the pack active, none of the changes take effect.
> Disabling the pack makes the skins render properly once more.
> 
> v1.16.210 on Windows 10

I can confirm the issue on Windows 10.

But it works on PS4! With BDS Server! Very happy about this, I'm mainly a PS4 Player. Nonetheless, issue with skin persists on PS4 as well. Still awesome work though! Thanks a lot!

Cheers kimon

**Comment by NeonTravler** [comment]
Confirmed same problem on Android

**Comment by MarkPuchalaII** [comment]
Confirmed same issue. 
Windows 10, Minecraft Bedrock 1.17.32.
Need any further information to debug?

**Comment by RavinMaddHatter** [comment]
Not fixable. It has to do with the way that market place skins work. If you
edit the player geometry it breaks market place skins
