### ISSUE TITLE
Gg

### ISSUE THREAD

**Issue by Dapolet** [RavinMaddHatter/Bedrock-Chunk-Boarders-Pack#5]
Gg

**Comment by RavinMaddHatter** [comment]
Please do not file bugs like this. It just clutters up my bug tracker

**Comment by Dapolet** [comment]
Sry man can you help me. How can I download it on iOS?

Вт, 3 авг. 2021 г. в 00:09, Mad Hatter ***@***.***>:

**Comment by RavinMaddHatter** [comment]
That isn't a bug. This is a bug tracker. There are many resources for how to install packs. I do not have ANY ios devices to try myself. 

Please stop using the bug tracker this way.

**Comment by Dapolet** [comment]
I tested all variants sry pls)

Вт, 3 авг. 2021 г. в 00:15, Mad Hatter ***@***.***>:

**Comment by RavinMaddHatter** [comment]
You are about to be banned from my git repositories. If i ban you from here you can never download any of my packs ever again. STOP USING THE BUG TRACKER LIKE THIS. 

If the next post you make is not a bug you will be banned. This will take away access to every pack i make ever.

DO NOT reply OK

**Comment by Dapolet** [comment]
No sorry please I was looking for all the options as can be downloaded on
IOS

Вт, 3 авг. 2021 г. в 00:41, Mad Hatter ***@***.***>:

**Comment by RavinMaddHatter** [comment]
you did not listen you will be banned now

**Comment by Dapolet** [comment]
Why?

Вт, 3 авг. 2021 г. в 00:45, Mad Hatter ***@***.***>:
