### ISSUE TITLE
How can i get the file

### ISSUE THREAD

**Issue by fransfrnso** [RavinMaddHatter/Bedrock-Chunk-Boarders-Pack#7]
How can i get the file@RavinMaddHatter

**Comment by AKWintermute** [comment]
Go to [Releases](https://github.com/RavinMaddHatter/Bedrock-Chunk-Boarders-Pack/releases) on the right side when you are on the [<>Code](https://github.com/RavinMaddHatter/Bedrock-Chunk-Boarders-Pack) tab.
